SET IDENTITY_INSERT [dbo].[Writers] ON
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (1, N'Ahmet', N'Yıldız', N'https://w7.pngwing.com/pngs/949/138/png-transparent-cartoon-businessperson-man-cartoon-miscellaneous-photography-hand-thumbnail.png', N'ahmetyildiz@gmail.com', N'1', N'Yazılım Mühendisi, Frontend Developer', NULL, 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (2, N'Mehmet', N'Çınar', N'https://w7.pngwing.com/pngs/511/1/png-transparent-man-wearing-black-suit-and-red-tie-cartoon-cartoon-business-man-business-woman-hand-people-thumbnail.png', N'mehmet@gmail.com', N'11', N'Senior Software Developer, bolca kitap okur.', NULL, 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (3, N'Aleyna', N'Öztürk', N'https://w7.pngwing.com/pngs/869/415/png-transparent-businessperson-cartoon-woman-business-woman-microphone-hand-thumbnail.png', N'aleyna@gmail.com', N'123', N'Tiyatro, filtre kahve', NULL, 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (4, N'Gizem', N'Ata', N'https://w7.pngwing.com/pngs/320/234/png-transparent-woman-cartoon-businessperson-drawing-woman-people-public-relations-business-thumbnail.png', N'gizem@gmail.com', N'10', N'Spor, bisiklet, dergiler ve karikatürler', NULL, 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (5, N'Aslı', N'Kaya', N'https://www.pngwing.com/en/free-png-dhins', N'asli@gmail.com', N'000', N'Kahve vazgeçilmezim, yanında bolca kod ile..', NULL, 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (6, N'Yılmaz', N'Çınar', N'https://w7.pngwing.com/pngs/117/139/png-transparent-man-holding-tablet-illustration-businessperson-character-business-man-take-hand-drawn-cartoon-ipad-cartoon-character-tshirt-electronics-thumbnail.png', N'yilmaz@gmail.com', N'1234', N'Angular, Vue, React ve diğerleri', NULL, 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (7, N'Admin', N'Admin', N'https://w7.pngwing.com/pngs/134/40/png-transparent-graphics-cartoon-drawing-man-thinking-cartoon-hand-photography-business-man-thumbnail.png', N'admin@gmail.com', N'01223334444', N'Admin', N'Admin', 0)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle], [WriterStatus]) VALUES (8, N'Şevval', N'Tek', N'https://w7.pngwing.com/pngs/731/993/png-transparent-woman-character-illustration-cartoon-woman-teacher-female-cartoon-female-teacher-cartoon-character-simple-cartoons-thumbnail.png', N'sevval@gmail.com', N'1905', N'Kitap, deniz ve müzik olsun yeter..', NULL, 0)
SET IDENTITY_INSERT [dbo].[Writers] OFF
