SET IDENTITY_INSERT [dbo].[Writers] ON
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (1, N'Ahmet', N'Yıldız', N'https://www.pngwing.com/en/free-png-vujid', N'ahmetyildiz@gmail.com', N'1', N'Yazılım Mühendisi, Frontend Developer', NULL)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (2, N'Mehmet', N'Çınar', N'https://www.pngwing.com/en/free-png-ymbla', N'mehmet@gmail.com', N'11', N'Senior Software Developer, bolca kitap okur.', NULL)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (3, N'Aleyna', N'Öztürk', N'https://www.pngwing.com/en/free-png-npwpe', N'aleyna@gmail.com', N'123', N'Tiyatro, filtre kahve', NULL)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (4, N'Gizem', N'Ata', N'https://www.pngwing.com/en/free-png-hauxv', N'gizem@gmail.com', N'10', N'Spor, bisiklet, dergiler ve karikatürler', NULL)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (5, N'Aslı', N'Kaya', N'https://www.pngwing.com/en/free-png-dhins', N'asli@gmail.com', N'000', N'Kahve vazgeçilmezim, yanında bolca kod ile..', NULL)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (6, N'Yılmaz', N'Çınar', N'https://www.pngwing.com/en/free-png-zamch', N'yilmaz@gmail.com', N'1234', N'Angular, Vue, React ve diğerleri', NULL)
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (7, N'Admin', N'Admin', N'https://www.pngwing.com/en/free-png-bwdjw', N'admin@gmail.com', N'01223334444', N'Admin', N'Admin')
INSERT INTO [dbo].[Writers] ([WriterID], [WriterName], [WriterSurname], [WriterImage], [WriterMail], [WriterPassword], [WriterAbout], [WriterTitle]) VALUES (8, N'Şevval', N'Tek', N'https://www.pngwing.com/en/free-png-bxkhl', N'sevval@gmail.com', N'1905', N'Kitap, deniz ve müzik olsun yeter..', NULL)
SET IDENTITY_INSERT [dbo].[Writers] OFF
