// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migwriter_addstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migwriter_addstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202107021436326_mig-writer_addstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
